server:
  port: 2333
lavalink:
  server:
    password: "towaynozomiv2"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
